name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set Node environment
        uses: actions/setup-node@master
        with:
          node-version: '18.x'

      - name: Install dependency
        working-directory: ./creating-front-end
        run: npm install

      - name: build
        working-directory: ./creating-front-end
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_OPTIMAP_376020 }}'
          channelId: live
          projectId: optimap-376020